name: Deploy Angular to S3

on:
  push:
    branches:
      - main  # se ejecuta cuando haces push a main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Instalar dependencias
        run: npm ci

      - name: Compilar Angular
        run: npm run build -- --configuration production

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Subir archivos a S3
        run: |
          aws s3 sync dist/smartinventoryappfront/browser/ s3://${{ secrets.S3_BUCKET }} --delete

      - name: Invalidar caché de CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
